FROM oven/bun:1.2.2

WORKDIR /usr/src/app
ARG DATABASE_URL

COPY . .



COPY apps/web ./apps/web

RUN bun install
RUN bun run db:generate
RUN DATABASE_URL=${DATABASE_URL}bun run db:migrate


EXPOSE 3000

CMD ["bun", "run", "start:frontend"]