FROM oven/bun:1.2.2

WORKDIR /app

COPY ./packages ./packages
COPY ./bun.lockb ./bun.lockb
COPY .package.json ./package.json
COPY .package-lock.json ./package-lock.json
COPY .turbo.json ./turbo.json



COPY apps/backend ./apps/backend

RUN bun install
RUN bun run db:generate


EXPOSE 8080

CMD ["bun", "run", "start:backend"]