## Build the docker image 
name: Build and Push Docker Image
on:
  push:
    branches:
      - main     
    paths:
      - 'apps/backend/**'
      - 'packages/db/**'
      - '.github/workflows/Cd_backend.yml'

jobs:    
  build-and-push-docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}   
          password: ${{ secrets.DOCKERHUB_TOKEN }}  

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./docker/Dockerfile.backend
          push: true        
          tags: kuldeep/app-backend:${{ github.sha }}
          ## Push the image to the registry